### PR TITLE
Use separate setting for main thumbnail size

### PR DESCRIPTION
**Pull request by stephywells**
Fixes https://github.com/Strategy11/BusinessDirectoryPlugin/issues/5130

This allows for the two different settings sizes to be used.

This rearranges the thumbnail settings and renames a couple settings:
- gallery thumbnail width/height
- Change "Directory thumb" in dropdown to "Default (size set below)"
- change "default thumbnail size" to "Main thumbnail inage size"

### CODE REVIEW

**Comment by garretlaxton** [comment]
Should each gallery image match the dimensions set in the gallery thumbnail settings? They seem to use their own sizing with a max of what's set in the gallery thumbnail settings.
localhost_bd-qa_business-real-estate-professionals-directory_lkjh_

For the main thumbnail images, I don't see the image sizes change. Just the width and height in the  tag changes.
e239808d3e79401ba32bb3ebe25ef45e

**Comment by stephywells** [comment]
@garretlaxton it depends. Do you have the crop toggle on too?

**Comment by garretlaxton** [comment]
I did not. When I enabled the crop option the images will use the max height, but the width stays at 150px.
localhost_bd-qa_business-real-estate-professionals-directory_lkjh_ (1)

Switching to no theme does show the main thumbnail images with their correct size. Wasn't aware of that.

**Comment by stephywells** [comment]
I did add a fix for that, but didn't compile the css. I just pushed that now. Does that help?

**Review by garretlaxton — APPROVED** [review]
Thanks! This looks great now!
localhost_bd-qa_business-real-estate-professionals-directory_lkjh_ (2)

**Pull request merged**
