### PR TITLE
Handle missing templates silently

### PR DESCRIPTION
**Pull request by theRealRizeo**
Removes exception thrown in case a template file does not exist.
If the file does not exist, return an empty string

### CODE REVIEW

**Comment by stephywells** [comment]
Was this causing a problem? Do you have more info on what was happening before?

**Comment by theRealRizeo** [comment]
Before if there was no file, it would show the WSOD and send the admin the error email to recover the site

**Comment by theRealRizeo** [comment]
I tested by changing or adding 1 word on the included template file, before the patch

**Comment by stephywells** [comment]
Was there a template that is missing? Or were you only seeing this during development?

**Comment by theRealRizeo** [comment]
Its related to this PR https://github.com/Strategy11/bd-business-card/pull/2#discussion_r773514879
It would be useful if an update is done and the template file does not exist

**Comment by stephywells** [comment]
Gotcha. Thanks for clearing that up! The PR looks good.

**Review by stephywells — APPROVED** [review]

**Pull request merged**
