### PR TITLE
Fix wordpress default theme styling

### PR DESCRIPTION
**Pull request by theRealRizeo**
Fixes styling on https://github.com/Strategy11/BusinessDirectoryPlugin/issues/4990

- Fixes Styling on 2019 theme
- Fixes styling on 2020 theme

Styling was mainly off when Zip Code search module is enabled.

### CODE REVIEW

**Comment by garretlaxton** [comment]
The 2020 theme looks great, the radius textbox isn't quite aligned on the 2019 theme though.
Screenshot 2021-11-03 at 18-46-46 BD QA – Just another WordPress site

**Comment by theRealRizeo** [comment]
Added some style font changes for large and smaller screens. Please check @garretlaxton :)

**Review by garretlaxton — APPROVED** [review]
Looks great!
Screenshot 2021-11-05 at 08-42-05 BD QA – Just another WordPress site

**Review by stephywells — APPROVED** [review]
Thanks Paul!

**Pull request merged**
