### PR TITLE
Issue 4950

### PR DESCRIPTION
**Pull request by stephywells**
Fixes https://github.com/Strategy11/BusinessDirectoryPlugin/issues/4950

The submit listing page should now be overridable.

I need to look into the difference between these two function more before merging. I don't understand why these would be used in different cases.

### CODE REVIEW

**Comment by stephywells** [comment]
@garretlaxton This should be better now. wp_render and wpbdp_x_part will both check the same places for template files.

The thing is, some template files are specifically excluded from getting overridden. That includes the submit-listing-images-upload-form and submit-listing templates. The thing is, that this can get too difficult to maintain if we let people override everything. Instead, I think we'll need more info on what people are trying to override in any templates that aren't currently allowed. Then we can take it on a case-by-case basis.

**Review by garretlaxton — APPROVED** [review]
Should we mention which templates aren't meant to be overridden in the docs? It may also be helpful if we get a ticket, we will know if that file can be overridden or not.

**Comment by stephywells** [comment]
It might be easier to list the files that can be overridden with a note that anything else most likely can't be overridden. Do you have more detail on what people were wanting to customize in the submit listing templates?

**Comment by garretlaxton** [comment]
@stephywells That will work too. The user was trying to change the order of the submit listing process.

**Comment by stephywells** [comment]
@garretlaxton Thanks for the extra detail. That isn't actually something that would be changed in the template. It would need to be done using a hook, or it would break things.

**Pull request merged**
