### PR TITLE
Remove abandonment hooks

### PR DESCRIPTION
**Pull request by theRealRizeo**
This removes the abandonment hooks migrated to https://github.com/Strategy11/business-directory-premium/pull/25

### CODE REVIEW

**Review by stephywells — CHANGES_REQUESTED** [review]
Thanks!

We'll need to leave all of the public functions to prevent fatal errors with possible reverse compatibility. But they can all be empty with just the deprecation message

**Comment by theRealRizeo** [comment]
@stephywells thanks for the feedback :) I have added the functions and deprecated them

**Review by stephywells — APPROVED** [review]
Thanks! That looks great now.

**Review by stephywells — APPROVED** [review]
Thanks! That's perfect now.

**Pull request merged**
