### PR TITLE
Fix the region page title issue on block themes

### PR DESCRIPTION
**Pull request by shervElmi**
With this PR, we will fix the region page title issue on block themes like 2023/2022 WP Themes.

### Issue Link:
https://github.com/Strategy11/business-directory-regions/issues/34

### CODE REVIEW

**Comment by garretlaxton** [comment]
The page title is correct, however the listing titles now show the region as well.
image

**Comment by shervElmi** [comment]
@garretlaxton It appears that the issue has been resolved in WordPress 6.2. Could you kindly verify this by checking the `master branch` using WordPress 6.2, along with the most recent versions of the WP 2023 and 2022 themes? Thank you.

**Comment by stephywells** [comment]
@shervElmi I haven't looked into this, so I don't have any other pointers at the moment.

**Comment by shervElmi** [comment]
Issues have been fixed in PR #300.

**Pull request closed without merging**
