### PR TITLE
fix title issue with the7 them in CPT mode

### PR DESCRIPTION
**Pull request by mostafa-hisham**
fix #[158](https://github.com/Strategy11/business-directory-premium/issues/158)
add a compatibility code to fix title issue with the & theme

### CODE REVIEW

**Comment by mostafa-hisham** [comment]
@garretlaxton could you please check this?
theme files are in the issue

**Comment by garretlaxton** [comment]
@mostafa-hisham Do you have steps to replicate this issue so I can test the fix? I currently see the title on listings before the changes.

**Comment by mostafa-hisham** [comment]
@garretlaxton 
- activate the Disable advanced CPT integration in BD settings
- visit category or listing page

**Review by garretlaxton — APPROVED** [review]
Thanks! This looks good!

**Review by stephywells — APPROVED** [review]
Nice fix! Thanks so much @mostafa-hisham !

**Pull request merged**
