### PR TITLE
Load Divi styling on category pages too

### PR DESCRIPTION
**Pull request by stephywells**
This fix loads the Divi global template on the category pages. This could use more testing on different setups.

### CODE REVIEW

**Comment by stephywells** [comment]
@garretlaxton I'd like to get this release out in the next hour or two. Would it be possible to test this so we can include it?

**Review by garretlaxton — APPROVED** [review]
This looks good, my Divi styles on BD pages seem to stick pretty well now.

**Comment by garretlaxton** [comment]
Nevermind, the cache made it look like it was fixed. I still see a different font on the menu for BD pages. https://qa.businessdirectoryplugin.com/business-directory/wpbdp_category/general/

**Comment by stephywells** [comment]
Thanks @garretlaxton ! I was testing with a global header. I ended up finding a better way of fixing this. Are you seeing any issues now?

**Review by garretlaxton — APPROVED** [review]
Okay, NOW the style is sticking to the pages! I looked though a bunch of other BD pages as well such as regions, tags, etc...

**Pull request merged**
